export const Medicines = [
  {
    name: "KN 95 Mask",
    url: "https://images-na.ssl-images-amazon.com/images/I/31tMI-F9iwL._AC_.jpg",
    id: 1,
    price: 70,
    para:"Approved for at least 95 percent filtration efficiency",
  },
  {
    name: "Dettol Hand Sanitizer",
    url: "https://media-services.digital-rb.com/s3/live-productcatalogue/sys-master/images/hd9/h6f/8848606035998/latest%20ad.jpg?width=320&height=320",
    id: 2,
    price: 40,
    para:"(500ml) Kills 99.9% of germs without water",
  },
  {
    name: "Pulse Oximeter",
    url: "https://m.media-amazon.com/images/I/51fLRJwD7mS._AC_UL480_FMwebp_QL65_.jpg",
    id: 3,
    price: 1499,
    para:"Measures accurate pulse rate and blood oxygen saturation",
  },
  {
    name: "Blood Pressure Monitor",
    url: "https://cdn.medlife.com/productImages/OMRONMD07A/OMRONMD07A.jpg?id=2021-05-17-20:40:29.064000",
    id: 4,
    price: 1876,
    para:"The HEM-6161 makes it easy to monitor blood pressure .",
  },
  {
    name: "Forever Bee Honey",
    url: "https://cdn.shopify.com/s/files/1/0464/2727/5428/products/Forever_bee_honey.png?v=1598449975",
    id: 5,
    price: 800,
    para:"Bees make honey by traveling from flower to flower.",
  },
  {
    name: "Zandu Giloy Capsules",
    url: "https://m.media-amazon.com/images/I/41UaXR8E7UL._AC_SR320,320_.jpg",
    id: 6,
    price: 249,
    para:"Protects Against Infections and Anti-Inflammatory",
  },
  {
    name: "Dabur Chyawanprash (1 kg)",
    url: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSyUARdwSSxaQeTu-6x0G3NqhVRwh4lJ05-a7PJqa1ewltKiKjqHw&usqp=CAc",
    id: 7,
    price: 310,
    para:"Strong immune system tackle viral fever, common cold, etc.",
  },
  {
    name: "PATANJALICORONIL KIT",
    url: "https://images-na.ssl-images-amazon.com/images/I/51Wk6KPa0vL._AC_.jpg",
    id: 8,
    price: 550,
    para:"A Patanjli product - 'BEST FOR IMMUNITY BOOSTER'",
  },
  {
    name: "CROCIN 650MG",
    url: "https://i-cf65ch.gskstatic.com/content/dam/cf-consumer-healthcare/panadol/en_in/adult/productshots/crocin650mg/455x455.jpg?auto=format",
    id: 9,
    price: 80,
    para:"Crocin 650mg tablets have higher dose of paracetamol ",
  },
  {
    name: "Himalayan Organics B- Complex",
    url: "https://cdn.shopify.com/s/files/1/0321/0264/5895/products/71on3py_QFL._SL1500_1024x1024_crop_center.jpg?v=1619461823",
    id: 10,
    price: 589,
    para: "FASTER METABOLISM, NATURAL AND GLUTEN-FREE etc.",
  },
  {
    name: "Natural Vitamin A",
    url: "https://cdn.shopify.com/s/files/1/2181/1153/products/Front_ba7a4e36-3c78-4b61-be15-b6c86f6467b6_4000x@2x.progressive.jpg?v=1601541442",
    id: 11,
    price: 630,
    para:"Highly Potent Anti-oxidant",
  },
  {
    name: "OZiva Bettr.Zinc+",
    url: "https://cdn.shopify.com/s/files/1/2393/2199/products/Zinc_476x@2x.progressive.jpg?v=1620722782",
    id: 12,
    price: 569,
    para:"Anti-inflammation and to help keep acne in control",
  },
];
